package test.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;
import xyz.navyd.mbg.entity.BaseEntit;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table bonus_event_log
 */
@Data
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
@NoArgsConstructor
public class BonusEventLog extends BaseEntit implements Serializable {
    private Long id;

    private Long userInfoId;

    private Integer bonusValue;

    private String bonusEvent;

    private String info;

    private LocalDateTime gmtCreate;

    private LocalDateTime gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bonus_event_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}