package test.model;

import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;
import xyz.navyd.mbg.entity.BaseEntity;

/**
 * Database Table Remarks:
 *   用户-分享中间表【描述用户购买的分享】
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table mid_user_share
 */
@Data
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
@NoArgsConstructor
public class MidUserShare extends BaseEntity implements Serializable {
    /**
     * share.id
     *
     * @mbg.generated
     */
    private Long shareInfoId;

    /**
     * user.id
     *
     * @mbg.generated
     */
    private Long userInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mid_user_share
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}