package test.model;

import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;
import xyz.navyd.mbg.entity.BaseEntity;

/**
 * Database Table Remarks:
 *   分享表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table share_info
 */
@Data
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
@NoArgsConstructor
public class ShareInfo extends BaseEntity implements Serializable {
    /**
     * 发布人id
     *
     * @mbg.generated
     */
    private Long userInfoId;

    /**
     * 标题
     *
     * @mbg.generated
     */
    private String title;

    /**
     * 是否原创 0:否 1:是
     *
     * @mbg.generated
     */
    private Boolean original;

    /**
     * 作者
     *
     * @mbg.generated
     */
    private String author;

    /**
     * 封面
     *
     * @mbg.generated
     */
    private String cover;

    /**
     * 概要信息
     *
     * @mbg.generated
     */
    private String summary;

    /**
     * 价格（需要的积分）
     *
     * @mbg.generated
     */
    private Integer price;

    /**
     * 下载地址
     *
     * @mbg.generated
     */
    private String downloadUrl;

    /**
     * 下载数 
     *
     * @mbg.generated
     */
    private Integer buyCount;

    /**
     * 是否显示 0:否 1:是
     *
     * @mbg.generated
     */
    private Boolean showFlag;

    /**
     * 审核状态 NOT_YET: 待审核 PASSED:审核通过 REJECTED:审核不通过
     *
     * @mbg.generated
     */
    private String auditStatus;

    /**
     * 审核不通过原因
     *
     * @mbg.generated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table share_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}