package test.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;
import xyz.navyd.mbg.entity.BaseEntit;

/**
 * Database Table Remarks:
 *   userinfo 表测试
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_info
 */
@Data
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
@NoArgsConstructor
public class UserInfo extends BaseEntit implements Serializable {
    /**
     * id工暮云春树
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * 法大师傅
     *
     * @mbg.generated
     */
    private String wxId;

    /**
     * 无可奈何花落去
     *
     * @mbg.generated
     */
    private String wxNickname;

    private String roles;

    /**
     * 幅度萨芬
     *
     * @mbg.generated
     */
    private String avatarUrl;

    /**
     * 无可奈何花落去
     *
     * @mbg.generated
     */
    private Integer bonus;

    /**
     * 克格勃
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    private LocalDateTime gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}